#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:url", "url")

#@ if "workshop-configuration.yaml" in data.list():
#@ config = yaml.decode(data.read("workshop-configuration.yaml")) or {}
#@ else:
#@ config = {}
#@ end

#@ params = json.decode(data.read("workshop-variables.json"))

#@ pathways = config.get("pathways", {}).get("paths", {})
#@ pathway_name = params.get("pathway_name", "")

#@ if not pathway_name and pathways:
#@   pathway_name = config.get("pathways", {}).get("default", "")
#@ end

#@ modules = config.get("pathways", {}).get("modules", {})

#@ path = pathways.get(pathway_name, {})

#@ steps = path.get("steps", [])

#@ active_modules = {}

#@ first_page = None
#@ prev_page = None

#@ count = 1

#@ for step in steps:
#@   if first_page == None:
#@     first_page = step
#@   end
#@   module = modules.get(step, {})
#@   module["path"] = step
#@   if prev_page != None:
#@     module["prev_page"] = prev_page
#@     active_modules[prev_page]["next_page"] = step
#@   else:
#@     module["prev_page"] = None
#@   end
#@   module["next_page"] = None
#@   module["step"] = count
#@   prev_page = step
#@   count = count + 1
#@   active_modules[step] = module
#@ end

#@ if first_page:
#@   params["__first_page__"] = first_page
#@   params["__modules__"] = active_modules
#@ else:
#@   params["__first_page__"] = ""
#@   params["__modules__"] = {}
#@ end

params: #@ params
