apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-extension-packages"
spec:
  title: "Extension Packages"
  description: "Overview of adding additional extension packages."
  duration: 30m
  publish:
    image: $(image_repository)/labs-educates-showcase/lab-extension-packages-files:$(workshop_version)
  workshop:
    files:
      - image:
          url: "$(image_repository)/labs-educates-showcase/lab-extension-packages-files:$(workshop_version)"
        includePaths:
          - /resources/**
          - /workshop/**
    packages:
      - name: educates
        files:
          - path: .
            image:
              url: ghcr.io/educates/educates-extension-packages/educates:v3.3.2
      - name: spring-academy-vscode-tools-via-overlay
        files:
          - path: .
            image:
              url: ghcr.io/educates/educates-extension-packages/vscode-java-tools-oci-overlay:v0.29.2
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      files:
        enabled: true
