apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-session-resources
spec:
  description: Overview of creating per session resources.
  duration: 30m
  session:
    applications:
      files:
        enabled: true
      terminal:
        enabled: true
        layout: split
    namespaces:
      budget: medium
  title: Session Resources
  version: 1.0.0
  workshop:
    files:
    - image:
        url: ghcr.io/educates/labs-educates-showcase/lab-session-resources-files:1.0.0
      includePaths:
      - /resources/**
      - /workshop/**
