apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "test-workshop"
spec:
  title: "Workshop"
  description: "Workshop description."
  publish:
    image: "$(image_repository)/test-workshop-files:$(workshop_version)"
  workshop:
    image: "$(image_repository)/base-image"
    files:
    - image:
        url: $(image_repository)/test-workshop-files:$(workshop_version)
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
      editor:
        enabled: true
      docker:
        enabled: true
      registry:
        enabled: true
