apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-k8s-fundamentals
spec:
  title: Kubernetes Fundamentals
  description: An interactive workshop on Kubernetes fundamentals.
  publish:
    image: $(image_repository)/lab-k8s-fundamentals-files:$(workshop_version)
    files:
    - directory:
        path: .
      includePaths:
      - /workshop/**
      - /templates/**
      - /README.md
  workshop:
    files:
    - image:
        url: $(image_repository)/lab-k8s-fundamentals-files:$(workshop_version)
      includePaths:
      - /workshop/**
      - /templates/**
      - /README.md
  session:
    namespaces:
      budget: medium
      security:
        policy: restricted
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
      slides:
        enabled: true
        reveal.js:
          version: 3.x
