name: linux
services:
  workshop:
    command:
    - bash
    - -c
    - |
      exec bash -s << "EOF"
      mkdir -p /opt/eduk8s/config
      cat > /opt/eduk8s/config/workshop.yaml << "EOS"
      spec:
        description: Workshop on essential Linux sysadmin skills
        session:
          applications:
            console:
              enabled: false
            docker:
              enabled: false
            editor:
              enabled: false
            examiner:
              enabled: true
            registry:
              enabled: false
            terminal:
              enabled: true
            vcluster:
              enabled: false
          dashboards: []
          ingresses: []
        title: Linux Workshop
      EOS
      cat > /opt/eduk8s/config/vendir-assets-01.yaml << "EOS"
      apiVersion: vendir.k14s.io/v1alpha1
      directories:
      - contents:
        - image:
            url: ghcr.io/sh3b0/linux-files:latest
          includePaths:
          - /workshop/**
          - /exercises/**
          - /README.md
          path: .
        path: /opt/assets/files
      kind: Config
      EOS
      exec start-container
      EOF
    image: sh3b0/base:latest
    networks:
      default: {}
    ports:
    - "8002:10081"
    user: "1001:0"
    volumes:
    - type: volume
      source: workshop
      target: /home/eduk8s
volumes:
  workshop: {}
