apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "exam"
spec:
  title: "Exam"
  description: "Using examiner to create an interactive test"
  publish:
    image: "ghcr.io/sh3b0/exam-files:latest"
  workshop:
    image: sh3b0/base:latest
    files:
    - image:
        url: "ghcr.io/sh3b0/exam-files:latest"
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
      editor:
        enabled: false
      docker:
        enabled: false
      examiner:
        enabled: true
      registry:
        enabled: false

