apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-virtual-machines
spec:
  description: Overview of provisioning virtual machines.
  duration: 30m
  environment:
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: datavolume-clone
      rules:
      - apiGroups:
        - kubevirt.io
        resources:
        - datavolume/source
        verbs:
        - get
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: ubuntu-22-04
      spec:
        pvc:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
        source:
          registry:
            url: docker://quay.io/containerdisks/ubuntu:22.04
  session:
    applications:
      examiner:
        enabled: true
      files:
        enabled: true
      terminal:
        enabled: true
        layout: split
    namespaces:
      budget: large
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: vmi-viewer
      rules:
      - apiGroups:
        - kubevirt.io
        resources:
        - virtualmachines
        - virtualmachineinstances
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - subresources.kubevirt.io
        resources:
        - virtualmachineinstances/console
        - virtualmachineinstances/filesystemlist
        - virtualmachineinstances/userlist
        verbs:
        - get
      - apiGroups:
        - subresources.kubevirt.io
        resources:
        - virtualmachines/restart
        verbs:
        - update
      - apiGroups:
        - subresources.kubevirt.io
        resources:
        - virtualmachineinstances/softreboot
        verbs:
        - update
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: vmi-viewer
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: vmi-viewer
      subjects:
      - kind: ServiceAccount
        name: $(service_account)
        namespace: $(workshop_namespace)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: $(session_namespace)-datavolume-clone
        namespace: $(workshop_namespace)
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: datavolume-clone
      subjects:
      - kind: ServiceAccount
        name: $(service_account)
        namespace: $(workshop_namespace)
    - apiVersion: secrets.educates.dev/v1beta1
      kind: SecretCopier
      metadata:
        name: $(session_namespace)-ssh-keys
      spec:
        rules:
        - sourceSecret:
            name: $(ssh_keys_secret)
            namespace: $(workshop_namespace)
          targetNamespaces:
            nameSelector:
              matchNames:
              - $(session_namespace)
          targetSecret:
            name: ssh-keys
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: vm-01
      spec:
        pvc:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
        source:
          pvc:
            name: ubuntu-22-04
            namespace: $(workshop_namespace)
    - apiVersion: kubevirt.io/v1
      kind: VirtualMachine
      metadata:
        labels:
          kubevirt.io/vm: vm-01
        name: vm-01
      spec:
        running: true
        template:
          metadata:
            labels:
              kubevirt.io/vm: vm-01
          spec:
            accessCredentials:
            - sshPublicKey:
                propagationMethod:
                  configDrive: {}
                source:
                  secret:
                    secretName: ssh-keys
            domain:
              cpu:
                cores: 2
              devices:
                disks:
                - disk:
                    bus: virtio
                  name: disk1
                - disk:
                    bus: virtio
                  name: cloudinitdisk
                interfaces:
                - masquerade: {}
                  name: default
              resources:
                limits:
                  memory: 2Gi
                requests:
                  memory: 2Gi
            networks:
            - name: default
              pod: {}
            terminationGracePeriodSeconds: 30
            volumes:
            - dataVolume:
                name: vm-01
              name: disk1
            - cloudInitConfigDrive:
                userData: |-
                  #cloud-config
                  password: $(services_password)
                  chpasswd: { expire: False }
                  runcmd:
                  - echo "set enable-bracketed-paste off" >> /etc/inputrc
              name: cloudinitdisk
    - apiVersion: v1
      kind: Service
      metadata:
        name: vm-01
      spec:
        ports:
        - name: ssh
          port: 22
          protocol: TCP
          targetPort: 22
        selector:
          kubevirt.io/vm: vm-01
  title: Virtual Machines
  version: 1.0.0
  workshop:
    files:
    - image:
        url: ghcr.io/educates/labs-educates-showcase/lab-virtual-machines-files:1.0.0
      includePaths:
      - /resources/**
      - /workshop/**
