apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "linux"
spec:
  title: "Linux Workshop"
  description: "Workshop on essential Linux sysadmin skills"
  publish:
    image: "$(image_repository)/linux-files:$(workshop_version)"
  workshop:
    files:
    - image:
        url: "$(image_repository)/linux-files:$(workshop_version)"
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      budget: medium
    applications:
      examiner:
        enabled: true
      terminal:
        enabled: true
      editor:
        enabled: false
      console:
        enabled: false
      docker:
        enabled: true
      registry:
        enabled: false
      vcluster:
        enabled: false

