apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "git"
spec:
  title: "git"
  description: "Workshop on Git"
  publish:
    image: "ghcr.io/sh3b0/git-files:latest"
  workshop:
    files:
    - image:
        url: "ghcr.io/sh3b0/git-files:latest"
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
      editor:
        enabled: false
      docker:
        enabled: false
      examiner:
        enabled: true
      registry:
        enabled: false
      git:
        enabled: true
